### PR TITLE
fixup! config-linux: Refined JSON definitions for RDMA limits

### PR DESCRIPTION
**Pull request by wking**
In case this is an easier way for me to make suggestions for opencontainers/runtime-spec#942.  If these changes look good, you can squash them into your master branch.

### CODE REVIEW

**Review by paravmellanox — COMMENTED** [review]
I followed HugepageLimits naming style to reflect as 'RdmaLimits' instead of 'Rdma'.

**Comment by wking** [comment]
On Wed, Jan 24, 2018 at 12:41:58PM -0800, Parav Pandit wrote:
> I followed HugepageLimits naming style to reflect as 'RdmaLimits'
> instead of 'Rdma'.

But the JSON property behind HugepageLimits is hugepageLimits [1].  I
think it would be fine to have:

  "rdma": {
    "mlx5_1": {
      "hca_handles": 3,
      "hca_objects": 10000
    },
    …
  }

with LinuxResources.Rdma.  Or it would be fine to have:

  "rdmaLimits": {
    "mlx5_1": {
      "hca_handles": 3,
      "hca_objects": 10000
    },
    …
  }

with LinuxResources.RdmaLimits.  But I'd rather not have ‘rdma’ as the
JSON property and RdmaLimits as the Go property.

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/specs-go/config.go#L336

**Comment by paravmellanox** [comment]
Ah I get now.
You are right.
So lets have:
LinuxResources.RdmaLimits as Go property
"rdmaLimits" as JSON property.

This aligns with hugepages naming convention well.

**Comment by wking** [comment]
On Wed, Jan 24, 2018 at 09:02:58PM +0000, Parav Pandit wrote:
> So lets have:
> LinuxResources.RdmaLimits as Go property
> "rdmaLimits" as JSON property.

Done with e28a297 → ff6d8ab.  I've also added the associated JSON
Schema and some tests to demonstrate additionalProperties working
(although you'll want to cherry-pick opencontainers/runtime-spec#945
for that).

**Review by paravmellanox — APPROVED** [review]

**Pull request merged**
